---
services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "gamified_trading"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  fastapi:
    build:
      context: .
    container_name: gamified_trading_fastapi
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8000/health]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres-db-volume:
